version: '3.8'

services:
    postgresdb:
        container_name: nodejs2024Q3-service_postgresDB_container
        build:
            context: postgres/
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file:
            - ./.env
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${POSTGRES_HOST}
        ports:
            - '${POSTGRES_PORT}:${POSTGRES_PORT}'
        volumes:
            - db:/var/lib/postgres/data
        networks:
            - postgres-network

    app:
        # ----- Local image ----- #
        container_name: nodejs2024Q3-service
        depends_on:
            - postgresdb
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file:
            - ./.env
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - .:/app
            - node-modules:/app/node_modules
        networks:
            - postgres-network

networks:
    postgres-network:
        driver: bridge

volumes:
    db:
    node-modules: