export const DEFAULT_PORT = 4000;
export const DEFAULT_CRYPT_SALT = 10;
export const DEFAULT_JWT_SECRET_KEY = 'JWT_SECRET_KEY';
export const DEFAULT_JWT_SECRET_REFRESH_KEY = 'JWT_SECRET_REFRESH_KEY';
export const DEFAULT_TOKEN_EXPIRE_TIME = '1h';
export const DEFAULT_TOKEN_REFRESH_EXPIRE_TIME = '24h';
export const DEFAULT_LOG_LEVEL = 'log';
export const DEFAULT_MAX_LOG_FILE_SIZE_IN_KB = '1000';
export const DEFAULT_MAX_LOG_FILES_COUNT = 10;

export default () => ({
  PORT: process.env.PORT ? parseInt(process.env.PORT, 10) : DEFAULT_PORT,

  CRYPT_SALT: process.env.CRYPT_SALT
    ? parseInt(process.env.CRYPT_SALT, 10)
    : DEFAULT_CRYPT_SALT,

  JWT_SECRET_KEY: process.env.JWT_SECRET_KEY || DEFAULT_JWT_SECRET_KEY,
  JWT_SECRET_REFRESH_KEY:
    process.env.JWT_SECRET_REFRESH_KEY || DEFAULT_JWT_SECRET_REFRESH_KEY,
  TOKEN_EXPIRE_TIME: process.env.TOKEN_EXPIRE_TIME || DEFAULT_TOKEN_EXPIRE_TIME,
  TOKEN_REFRESH_EXPIRE_TIME: process.env.TOKEN_REFRESH_EXPIRE_TIME || DEFAULT_TOKEN_REFRESH_EXPIRE_TIME,

  LOG_LEVEL: process.env.LOG_LEVEL || DEFAULT_LOG_LEVEL,
  MAX_LOG_FILE_SIZE_IN_KB: process.env.MAX_LOG_FILE_SIZE_IN_KB
    ? parseInt(process.env.MAX_LOG_FILE_SIZE_IN_KB, 10)
    : DEFAULT_MAX_LOG_FILE_SIZE_IN_KB,
  MAX_LOG_FILES_COUNT: process.env.MAX_LOG_FILES_COUNT
    ? parseInt(process.env.MAX_LOG_FILES_COUNT)
    : DEFAULT_MAX_LOG_FILES_COUNT,
});
